import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hunglydev_datn/core/constant/constant.dart';
import 'package:hunglydev_datn/core/constant/src/app_images.dart';
import 'package:hunglydev_datn/core/utils/utils.dart';
import 'package:hunglydev_datn/core/widget/widget.dart';
import 'package:hunglydev_datn/enums/enum.dart';
import 'package:hunglydev_datn/extension/context_extension.dart';
import 'package:hunglydev_datn/features/blood_pressure/data/models/blood_pressure.dart';
import 'package:hunglydev_datn/features/blood_pressure/presentation/bloc/blood_pressure_bloc.dart';
import 'package:hunglydev_datn/generated/l10n.dart';
import 'package:intl/intl.dart';

part 'page.dart';
part 'widget/blood_pressure_data_widget.dart';
part 'widget/systolic_diastolic_widget.dart';
part 'widget/add_blood_pressure/page.dart';
part 'widget/add_blood_pressure/scroll_blood_pressure_value.dart';
